### PR TITLE
smoothly added a boolean switch between green and red dots

### PR DESCRIPTION
**Pull request by Rajveer07**
Issue: #4 

image
 changing the value of status we could change the dot .  Either we could change the value of status manually directly from the code or we could create a schema in database with name status and fetch the value of status from database . It will be blue or red according to the true or false value of the status.

### CODE REVIEW

**Comment by sarkartanmay393** [comment]
@Rajveer07 Your code has a build error. Can you fix it?

**Comment by Rajveer07** [comment]
what is the errror 

> @Rajveer07 Your code has a build error. Can you fix it?

what is that error

**Comment by Rajveer07** [comment]
@sarkartanmay393 the build error has been resolved check it out

**Comment by Rajveer07** [comment]
hello

**Pull request closed without merging**
